### PR TITLE
Disregard (moved to github.com/Flibber)

### PR DESCRIPTION
**Pull request by ChipWolf**
## DISREGARD

### CODE REVIEW

**Comment by MichaelBanks** [comment]
//cc. @mutlu82 @oh_moore

**Comment by oleg-koval** [comment]
@MichaelBanks 
Also I would recommend to pass all input data such as time delays, tokens etc in some json file in other file to make some decouple of static variables

Also I need to ask You is it necessary to use pycurl?

**Comment by MichaelBanks** [comment]
@redbonesmith I could, but pycurl is honestly the best option for this application. urllib doesn't suit.

**Comment by oleg-koval** [comment]
@MichaelBanks  OK, cool! will use Yours code to make new improvements too, 
update here when you will finish please

**Comment by MichaelBanks** [comment]
@redbonesmith just fixing bugs atm. Will be shifting stuff off to another file in a bit.

**Comment by MichaelBanks** [comment]
@redbonesmith moving stuff over to https://github.com/Flibber/Flibber

**Pull request closed without merging**
